[build-system]
requires = ["setuptools >= 77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "solvtext"
version = "0.0.1"
dependencies = [
  "rich",
  "numpy",
]

[project.scripts]
solvtext = "solvtext.solve:main"

[tool.setuptools]
packages = ["solvtext"]
